services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: fastapi_app
    volumes:
      - ./backend/src/:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
